### PR TITLE
Js3 W1 Homework

### PR DESCRIPTION
**Pull request by ersarue**

### CODE REVIEW

**Comment by ersarue** [comment]
Dear Jim, somehow my cloned repository missed some line of codes without my input, thus I have to copy all default lines manually. This could have caused issues behind the scenes, I am yet to know.

**Comment by ersarue** [comment]
And I didn’t add styling in CSS for responsiveness because I tried different window sizes in console and saw it’s already responsive

**Comment by remarcmij** [comment]
There is an additional problem with your fork of the JavaScript3 repo. It is out of date, probably because you forked it more than two weeks ago. I update the repo on 8 September and your fork is missing the latest changes that you require to do the homework.

It is best if you rename the local folder that contains your clone repo, say from JavaScript3 to JavaScript3_bkup. Then remove the fork on GitHub, fork the update repo again from the GitHub HYF page, clone again and copy the code you modified from the backup copy to the new copy.

Then close the pull request and create a new one from your new repo.

**Comment by ersarue** [comment]
Dear Jim, that's correct indeed. I have done the cloning before that time. I am gonna apply your instructions and submit the homework asap.

**Pull request closed without merging**
