### PR TITLE
Irfan-Week2

### PR DESCRIPTION
**Pull request by irfankaradeniz**

### CODE REVIEW

**Comment by irfankaradeniz** [comment]
Thanks for your feedback Jim. I think there is a misunderstanding of my purpose. I intentionally derived your code into my work. Because I found it more efficient for understanding the concepts of promises by writing each line of code one by one and also examining it.

**Comment by remarcmij** [comment]
Hi Irfan, can I ask you how you obtained this code? As far as I know, it has not been made available generally.

**Comment by irfankaradeniz** [comment]
https://www.youtube.com/watch?v=JhHw0xFarws - Here is the link that you recorded in the lesson. I did the homework by watching this video.

**Comment by remarcmij** [comment]
We need not continue the discussion here. But for instance, the `addRow` function and the way the exception for the first row is handled was not covered in the lecture and is too unique for you to have developed independently. It comes verbatim from my unpublished solution code as evidenced by the picture.

**Pull request closed without merging**
